    - name: Run tests with coverage (try, hard timeout)
      id: test_with_cov
      continue-on-error: true
      run: |
        timeout 480s npx vitest run \
          --coverage \
          --coverage.reporter=text-summary,lcov \
          --coverage.reportsDirectory=coverage \
          --reporter=dot \
          --silent \
          --sequence.concurrent=false \
          --pool=forks \
          --testTimeout=30000

    - name: Fallback tests (no coverage, hard timeout)
      if: ${{ steps.test_with_cov.outcome == 'failure' }}
      run: |
        timeout 300s npx vitest run \
          --reporter=dot \
          --silent \
          --sequence.concurrent=false \
          --pool=forks \
          --testTimeout=30000

    - name: List coverage (debug)
      if: ${{ hashFiles('coverage/**') != '' }}
      run: ls -la coverage

    - name: Upload coverage report
      if: ${{ hashFiles('coverage/**') != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
        if-no-files-found: warn
