name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Run CI script
      run: npm run ci

    - name: Verify build artifacts
      run: |
        test -d dist
        test -f dist/index.html
        echo "✅ Build successful"

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage

    # Optional: integration reporter
    - name: Run tests (verbose)
      if: always()
      run: npm run test:run -- --reporter=verbose

    

  