name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: TypeScript compilation check
      run: npx tsc --noEmit
      
    - name: Run tests
      run: npm run test:run
      
    - name: Build project
      run: npm run build
      
    - name: Verify build artifacts
      run: |
        test -d dist
        test -f dist/index.html
        echo "✅ Build successful"
    
    - name: Run unit tests
      run: npm run test:run

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Enforce coverage threshold (statements >= 70%)
      if: always()
      run: node -e "const r=require('./coverage/coverage-summary.json');const p=r.total.statements.pct; if(p<70){console.error('Coverage bajo:',p);process.exit(1)} else {console.log('Coverage OK:',p)}"

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage