name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# 🔁 Cancela ejecuciones anteriores en la misma rama
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Build project
      run: npm run build

    - name: Verify build artifacts
      run: |
        test -d dist
        test -f dist/index.html
        echo "✅ Build successful"

    - name: Run tests (with coverage, safe mode)
      # Ejecuta las pruebas sin colgarse
      run: npx vitest run --coverage --maxWorkers=2 --runInBand --reporter=verbose --testTimeout=30000

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
